<?php

namespace PerfexMcp\Tools;

use PerfexMcp\Auth\ReadScope;

/**
 * Knowledge base articles and their groups.
 *
 * Perfex keys these tables by articleid / groupid rather than id; the tools
 * accept and return "id" and map internally, and every row also carries the
 * native key. Article bodies are editor HTML and are returned verbatim.
 * Slugs are generated by the model on create (slug_it + collision suffix)
 * and deliberately never regenerated on update - a published URL stays
 * stable when a subject is edited. The permission feature "knowledge_base"
 * has no view_own.
 */
final class KnowledgeBaseTools extends AbstractTools
{
    private const ARTICLE_COLUMNS = 'articleid, articlegroup, subject, slug, active, datecreated, article_order, staff_article';
    private const GROUP_COLUMNS   = 'groupid, name, group_slug, description, active, color, group_order';

    // ------------------------------------------------------------------ reads

    public function knowledge_base_list(?int $group_id = null, ?bool $active = null, ?string $search = null, int $limit = 25, int $offset = 0): array
    {
        return $this->guard('knowledge_base_list', ['read', 'knowledge_base'], compact('group_id', 'active', 'search', 'limit', 'offset'), function (ReadScope $scope) use ($group_id, $active, $search, $limit, $offset) {
            $result = $this->paginate(
                $scope,
                db_prefix() . 'knowledge_base',
                self::ARTICLE_COLUMNS,
                function ($db) use ($group_id, $active, $search) {
                    if ($group_id !== null) {
                        $db->where('articlegroup', $group_id);
                    }
                    if ($active !== null) {
                        $db->where('active', $active ? 1 : 0);
                    }
                    if ($search !== null && $search !== '') {
                        $db->like('subject', $search);
                    }
                },
                // Per-field direction with an empty direction argument (CI3
                // only parses per-field ASC/DESC that way).
                'article_order asc, articleid asc',
                '',
                $limit,
                $offset
            );
            $result['data'] = $this->decorateLookup($result['data'], 'knowledge_base_groups', 'articlegroup', 'name', 'group_name', 'groupid');
            foreach ($result['data'] as &$row) {
                $row['id'] = (int) $row['articleid'];
            }

            return $result;
        });
    }

    public function knowledge_base_get(int $id): array
    {
        return $this->guard('knowledge_base_get', ['view', 'knowledge_base'], compact('id'), function () use ($id) {
            $article       = $this->requireRow('knowledge_base', $id, 'Article', 'articleid');
            $article['id'] = (int) $article['articleid'];

            $this->CI->db->where('groupid', (int) $article['articlegroup']);
            $group            = $this->CI->db->get(db_prefix() . 'knowledge_base_groups')->row_array();
            $article['group'] = $group
                ? ['id' => (int) $group['groupid'], 'name' => $group['name'], 'active' => (int) $group['active']]
                : null;
            if ($group === null) {
                $article['warning'] = 'Group no longer exists; the article is not reachable in the knowledge base until articlegroup is fixed via knowledge_base_update.';
            }

            return ['article' => $article];
        });
    }

    public function knowledge_base_groups_list(?bool $active = null, int $limit = 25, int $offset = 0): array
    {
        return $this->guard('knowledge_base_groups_list', ['read', 'knowledge_base'], compact('active', 'limit', 'offset'), function (ReadScope $scope) use ($active, $limit, $offset) {
            $result = $this->paginate(
                $scope,
                db_prefix() . 'knowledge_base_groups',
                self::GROUP_COLUMNS,
                function ($db) use ($active) {
                    if ($active !== null) {
                        $db->where('active', $active ? 1 : 0);
                    }
                },
                'group_order asc, groupid asc',
                '',
                $limit,
                $offset
            );
            foreach ($result['data'] as &$row) {
                $row['id'] = (int) $row['groupid'];
            }

            return $result;
        });
    }

    // ----------------------------------------------------------------- writes

    public function knowledge_base_create(array $fields): array
    {
        return $this->guard('knowledge_base_create', ['create', 'knowledge_base'], compact('fields'), function () use ($fields) {
            $this->requireFields($fields, ['subject', 'description', 'articlegroup']);
            $groupId = (int) $fields['articlegroup'];
            $this->requireRow('knowledge_base_groups', $groupId, 'Knowledge base group', 'groupid');

            $data = [
                'subject'      => (string) $fields['subject'],
                'description'  => (string) $fields['description'],
                'articlegroup' => $groupId,
            ];
            // CHECKBOX PRESENCE SEMANTICS in add_article(): "disabled" present
            // -> active 0, "staff_article" present -> 1.
            $data = $this->setCheckboxFlag($data, 'disabled', isset($fields['active']) && ! $fields['active']);
            $data = $this->setCheckboxFlag($data, 'staff_article', ! empty($fields['staff_article']));

            $this->CI->load->model('knowledge_base_model');
            $id = $this->CI->knowledge_base_model->add_article($data);
            if (! $id) {
                $this->fail('Failed to create article.');
            }

            $this->CI->db->where('articleid', (int) $id);
            $row = $this->CI->db->get(db_prefix() . 'knowledge_base')->row_array();

            return ['created' => true, 'id' => (int) $id, 'slug' => $row['slug'] ?? null];
        });
    }

    public function knowledge_base_update(int $id, array $fields): array
    {
        return $this->guard('knowledge_base_update', ['edit', 'knowledge_base'], compact('id', 'fields'), function () use ($id, $fields) {
            $allowed = ['subject', 'description', 'articlegroup', 'active', 'staff_article', 'article_order'];
            $data    = $this->pickAllowed($fields, $allowed);
            if ($data === []) {
                $this->fail('No updatable fields provided (allowed: ' . implode(', ', $allowed) . ').');
            }
            $this->requireRow('knowledge_base', $id, 'Article', 'articleid');

            if (array_key_exists('subject', $data) && trim((string) $data['subject']) === '') {
                $this->fail('subject cannot be empty.');
            }
            if (array_key_exists('articlegroup', $data)) {
                $data['articlegroup'] = (int) $data['articlegroup'];
                $this->requireRow('knowledge_base_groups', $data['articlegroup'], 'Knowledge base group', 'groupid');
            }
            foreach (['active', 'staff_article'] as $flag) {
                if (array_key_exists($flag, $data)) {
                    $data[$flag] = empty($data[$flag]) ? 0 : 1;
                }
            }
            if (array_key_exists('article_order', $data)) {
                $data['article_order'] = max(0, (int) $data['article_order']);
            }

            $this->CI->db->where('articleid', $id);
            $ok = $this->CI->db->update(db_prefix() . 'knowledge_base', $data);

            return ['updated' => (bool) $ok, 'id' => $id];
        });
    }

    public function knowledge_base_groups_create(array $fields): array
    {
        return $this->guard('knowledge_base_groups_create', ['create', 'knowledge_base'], compact('fields'), function () use ($fields) {
            $this->requireFields($fields, ['name']);
            $name = trim((string) $fields['name']);

            // Idempotent bootstrap, matching expense_categories_create.
            $this->CI->db->where('LOWER(name)', mb_strtolower($name));
            $existing = $this->CI->db->get(db_prefix() . 'knowledge_base_groups')->row_array();
            if ($existing) {
                return ['created' => false, 'existing' => true, 'id' => (int) $existing['groupid']];
            }

            $data = [
                'name'        => $name,
                'description' => isset($fields['description']) ? (string) $fields['description'] : '',
            ];
            if (isset($fields['color']) && $fields['color'] !== '') {
                if (! preg_match('/^#[0-9a-f]{6}$/i', (string) $fields['color'])) {
                    $this->fail('color must be a hex colour like #28B8DA.');
                }
                $data['color'] = (string) $fields['color'];
            }
            $data = $this->setCheckboxFlag($data, 'disabled', isset($fields['active']) && ! $fields['active']);

            $this->CI->load->model('knowledge_base_model');
            $id = $this->CI->knowledge_base_model->add_group($data);
            if (! $id) {
                $this->fail('Failed to create knowledge base group.');
            }

            return ['created' => true, 'id' => (int) $id];
        });
    }

    // ------------------------------------------------------------ destructive

    public function knowledge_base_delete(int $id, bool $confirm = false): array
    {
        return $this->guard('knowledge_base_delete', ['delete', 'knowledge_base'], compact('id', 'confirm'), function () use ($id, $confirm) {
            $this->requireDestructive($confirm);
            $this->requireRow('knowledge_base', $id, 'Article', 'articleid');

            $this->CI->load->model('knowledge_base_model');
            $ok = $this->CI->knowledge_base_model->delete_article($id);

            return ['deleted' => (bool) $ok, 'id' => $id];
        });
    }
}
